/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DBox: typeof import('./src/components/DBox/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElRow: typeof import('element-plus/es')['ElRow']
    'IMaterialSymbols:10k': typeof import('~icons/material-symbols/10k')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    'ITwemoji:mirrorBall': typeof import('~icons/twemoji/mirror-ball')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    ModelView: typeof import('./src/components/modelView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/layout/sidebarItem.vue')['default']
    SidebarTree: typeof import('./src/components/layout/sidebarTree.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
  }
}
